---
title: "Themed Dashboard"
format: 
    dashboard:
        theme: sketchy
        vertical_layout: fill
---

```{r setup}
#| include: false

library(palmerpenguins)
library(ggplot2)
library(dplyr)
library(leaflet) # interactive maps
library(plotly) # interactive plots
```

```{r}
#| include: false
# save data to object
penguin_df <- palmerpenguins::penguins

glimpse(penguin_df)

```

## Row 1 {height=20%}


### Chart A

```{r}
#| content: valuebox
#| title: "Total Number with Female Penguins"

penguin_female <- penguin_df %>% 
    group_by(sex) %>% 
    tally() %>% 
    filter(sex == "female") %>% 
    #select (n) %>% 
    pull() #turns dataframe into vecttor

penguin_female2 <- penguin_df %>% 
    count(sex) %>% 
    filter(sex == "female") %>% 
    pull() #turns dataframe into vector


list(
  icon = "hash",
  color = "warning",
  value = penguin_female
)

```

### Chart B

```{r}
#| content: valuebox
#| title: "Total Number with Male Penguins"

penguin_male <- penguin_df %>% 
    group_by(sex) %>% 
    tally() %>% 
    filter(sex == "male") %>% 
    #select (n) %>% 
    pull() #turns dataframe into vecttor

penguin_male2 <- penguin_df %>% 
    count(sex) %>% 
    filter(sex == "male") %>% 
    pull() #turns dataframe into vector


list(
  icon = "hash",
  color = "blue",
  value = penguin_male
)
```

